apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: default
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 78855e18-21c4-4512-8ede-e97bde25dfc3
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000